export const supportTickets = [
    {
        id: 'TK-2847',
        date: "2022-01-01",
        title: 'Payment Gateway Integration Issue',
        agency: 'Digital Solutions Inc',
        priority: 'Critical',
        status: 'In Progress',
        description: 'Payment processing fails intermittently on checkout page. Users are reporting timeout errors when attempting to use credit cards.',
        timeAgo: '2 hours ago',
        comments: 5,
        files: 3,
        assignee: { name: 'Mike Chen', avatar: 'https://i.pravatar.cc/150?u=mike' },
        reporter: { name: 'Sarah Connor', avatar: 'https://i.pravatar.cc/150?u=sarah' },
        slaRemaining: '4h remaining',
        slaPercentage: 80,
        timeline: [
            { title: 'Ticket created', time: '2 hours ago', active: true },
            { title: 'Assigned to Mike Chen', time: '1 hour ago', active: false },
            { title: 'Investigating logs', time: '30 mins ago', active: false }
        ],
        attachments: [
            { name: 'screenshot_error.png', size: '1.2 MB' },
            { name: 'console_logs.txt', size: '45 KB' }
        ]
    },
    {
        id: 'TK-2846',
        date: "2022-01-01",
        title: 'Email Notifications Not Working',
        agency: 'Creative Hub',
        priority: 'High',
        status: 'Open',
        description: 'Users reporting they\'re not receiving email notifications for new messages. Issue started after the recent deployment.',
        timeAgo: '4 hours ago',
        comments: 2,
        files: 1,
        assignee: { name: 'Sarah Johnson', avatar: 'https://i.pravatar.cc/150?u=sarahj' },
        reporter: { name: 'John Doe', avatar: 'https://i.pravatar.cc/150?u=john' },
        slaRemaining: '12h remaining',
        slaPercentage: 30,
        timeline: [
            { title: 'Ticket created', time: '4 hours ago', active: true },
            { title: 'Assigned to Sarah Johnson', time: '2 hours ago', active: false }
        ],
        attachments: [
            { name: 'user_reports.csv', size: '120 KB' }
        ]
    },
    {
        id: 'TK-2845',
        date: "2022-01-01",
        title: 'Dashboard Loading Slowly',
        agency: 'Tech Innovations',
        priority: 'Medium',
        status: 'Pending',
        description: 'Dashboard takes 10+ seconds to load with large datasets. Needs optimization on the analytics queries.',
        timeAgo: '6 hours ago',
        comments: 8,
        files: 2,
        assignee: { name: 'David Park', avatar: 'https://i.pravatar.cc/150?u=david' },
        reporter: { name: 'Alice Smith', avatar: 'https://i.pravatar.cc/150?u=alice' },
        slaRemaining: '24h remaining',
        slaPercentage: 15,
        timeline: [
            { title: 'Ticket created', time: '6 hours ago', active: true },
            { title: 'Performance profiling started', time: '4 hours ago', active: false },
            { title: 'Waiting for DB team input', time: '1 hour ago', active: false }
        ],
        attachments: [
            { name: 'query_profile.pdf', size: '2.4 MB' }
        ]
    },
    {
        id: 'TK-2844',
        date: "2022-01-01",
        title: 'Add Export to CSV Feature',
        agency: 'Marketing Pro',
        priority: 'Low',
        status: 'Resolved',
        description: 'Request to add CSV export functionality to reports section so we can import into our external BI tools.',
        timeAgo: '1 day ago',
        comments: 12,
        files: 0,
        assignee: { name: 'Sarah Johnson', avatar: 'https://i.pravatar.cc/150?u=sarahj' },
        reporter: { name: 'Bob Wilson', avatar: 'https://i.pravatar.cc/150?u=bob' },
        slaRemaining: 'Resolved',
        slaPercentage: 100,
        timeline: [
            { title: 'Ticket created', time: '3 days ago', active: false },
            { title: 'Feature deployed', time: '1 day ago', active: false },
            { title: 'Ticket closed', time: '1 day ago', active: true }
        ],
        attachments: []
    },
    {
        id: 'TK-2843',
        date: "2022-01-01",
        title: 'Mobile App Crashes on iOS 17',
        agency: 'Digital Solutions Inc',
        priority: 'High',
        status: 'In Progress',
        description: 'App crashes when opening profile page on iOS 17 devices. Stack trace points to a memory leak in the image renderer.',
        timeAgo: '2 days ago',
        comments: 15,
        files: 4,
        assignee: { name: 'Mike Chen', avatar: 'https://i.pravatar.cc/150?u=mike' },
        reporter: { name: 'Eve Davis', avatar: 'https://i.pravatar.cc/150?u=eve' },
        slaRemaining: 'Overdue',
        slaPercentage: 100,
        timeline: [
            { title: 'Ticket created', time: '2 days ago', active: false },
            { title: 'Reproduced bug', time: '1 day ago', active: false },
            { title: 'Working on patch', time: '5 hours ago', active: true }
        ],
        attachments: [
            { name: 'crash_log_1.txt', size: '1.1 MB' },
            { name: 'crash_log_2.txt', size: '900 KB' }
        ]
    },
    {
        id: 'TK-2842',
        date: "2023-05-12",
        title: 'User Sync Failure',
        agency: 'Alpha Corp',
        priority: 'High',
        status: 'Open',
        description: 'Scheduled user sync from active directory failed last night.',
        timeAgo: '5 hours ago',
        comments: 1,
        files: 0,
        assignee: { name: 'Sarah Johnson', avatar: 'https://i.pravatar.cc/150?u=sarahj' },
        reporter: { name: 'Admin', avatar: 'https://i.pravatar.cc/150?u=admin' },
        slaRemaining: '10h remaining',
        slaPercentage: 40,
        timeline: [],
        attachments: []
    },
    {
        id: 'TK-2841',
        date: "2023-05-15",
        title: 'SSO Login Error',
        agency: 'Tech Innovations',
        priority: 'Critical',
        status: 'In Progress',
        description: 'Users cannot log in via SAML SSO. Identity provider returns 500 error.',
        timeAgo: '1 hour ago',
        comments: 4,
        files: 2,
        assignee: { name: 'Mike Chen', avatar: 'https://i.pravatar.cc/150?u=mike' },
        reporter: { name: 'Bob Wilson', avatar: 'https://i.pravatar.cc/150?u=bob' },
        slaRemaining: '2h remaining',
        slaPercentage: 90,
        timeline: [],
        attachments: []
    },
    {
        id: 'TK-2840',
        date: "2023-06-01",
        title: 'Missing Report Data',
        agency: 'Digital Solutions Inc',
        priority: 'Medium',
        status: 'Pending',
        description: 'Monthly activity report is missing records for the last 3 days of the month.',
        timeAgo: '2 days ago',
        comments: 6,
        files: 1,
        assignee: { name: 'David Park', avatar: 'https://i.pravatar.cc/150?u=david' },
        reporter: { name: 'Eve Davis', avatar: 'https://i.pravatar.cc/150?u=eve' },
        slaRemaining: '48h remaining',
        slaPercentage: 20,
        timeline: [],
        attachments: []
    },
    {
        id: 'TK-2839',
        date: "2023-06-10",
        title: 'API Rate Limit Exceeded',
        agency: 'Creative Hub',
        priority: 'Low',
        status: 'Resolved',
        description: 'Agency hit API rate limits repeatedly. Requested temporary increase.',
        timeAgo: '1 week ago',
        comments: 3,
        files: 0,
        assignee: { name: 'Sarah Johnson', avatar: 'https://i.pravatar.cc/150?u=sarahj' },
        reporter: { name: 'John Doe', avatar: 'https://i.pravatar.cc/150?u=john' },
        slaRemaining: 'Resolved',
        slaPercentage: 100,
        timeline: [],
        attachments: []
    },
    {
        id: 'TK-2838',
        date: "2023-07-02",
        title: 'Password Reset Link Expired',
        agency: 'Marketing Pro',
        priority: 'Medium',
        status: 'Open',
        description: 'Users complaining that password reset links expire within 5 minutes instead of 24 hours.',
        timeAgo: '4 hours ago',
        comments: 0,
        files: 0,
        assignee: { name: 'Mike Chen', avatar: 'https://i.pravatar.cc/150?u=mike' },
        reporter: { name: 'Alice Smith', avatar: 'https://i.pravatar.cc/150?u=alice' },
        slaRemaining: '20h remaining',
        slaPercentage: 10,
        timeline: [],
        attachments: []
    },
    {
        id: 'TK-2837',
        date: "2023-07-15",
        title: 'Two-Factor Auth Timeout',
        agency: 'Alpha Corp',
        priority: 'High',
        status: 'In Progress',
        description: 'SMS codes for 2FA are arriving 10 minutes late, causing login timeouts.',
        timeAgo: '3 hours ago',
        comments: 8,
        files: 0,
        assignee: { name: 'David Park', avatar: 'https://i.pravatar.cc/150?u=david' },
        reporter: { name: 'Sarah Connor', avatar: 'https://i.pravatar.cc/150?u=sarah' },
        slaRemaining: '5h remaining',
        slaPercentage: 60,
        timeline: [],
        attachments: []
    },
    {
        id: 'TK-2836',
        date: "2023-08-01",
        title: 'Data Export Corrupted',
        agency: 'Tech Innovations',
        priority: 'Critical',
        status: 'Open',
        description: 'CSV exports from the billing page contain malformed characters.',
        timeAgo: '30 mins ago',
        comments: 2,
        files: 2,
        assignee: { name: 'Sarah Johnson', avatar: 'https://i.pravatar.cc/150?u=sarahj' },
        reporter: { name: 'Bob Wilson', avatar: 'https://i.pravatar.cc/150?u=bob' },
        slaRemaining: '3h remaining',
        slaPercentage: 85,
        timeline: [],
        attachments: []
    },
    {
        id: 'TK-2835',
        date: "2023-08-10",
        title: 'Webhook Delivery Failed',
        agency: 'Digital Solutions Inc',
        priority: 'High',
        status: 'Pending',
        description: 'Payment success webhooks are not reaching the agency endpoints. Retries fail.',
        timeAgo: '5 hours ago',
        comments: 5,
        files: 1,
        assignee: { name: 'Mike Chen', avatar: 'https://i.pravatar.cc/150?u=mike' },
        reporter: { name: 'Eve Davis', avatar: 'https://i.pravatar.cc/150?u=eve' },
        slaRemaining: '7h remaining',
        slaPercentage: 50,
        timeline: [],
        attachments: []
    },
    {
        id: 'TK-2834',
        date: "2023-08-20",
        title: 'Billing Invoice Discrepancy',
        agency: 'Creative Hub',
        priority: 'Medium',
        status: 'Open',
        description: 'Last month invoice charged for 5 extra seats that were not provisioned.',
        timeAgo: '1 day ago',
        comments: 3,
        files: 1,
        assignee: { name: 'David Park', avatar: 'https://i.pravatar.cc/150?u=david' },
        reporter: { name: 'John Doe', avatar: 'https://i.pravatar.cc/150?u=john' },
        slaRemaining: '48h remaining',
        slaPercentage: 30,
        timeline: [],
        attachments: []
    },
    {
        id: 'TK-2833',
        date: "2023-09-05",
        title: 'UI Glitch on Settings Page',
        agency: 'Marketing Pro',
        priority: 'Low',
        status: 'Resolved',
        description: 'Save button on settings page was disabled visually but still clickable.',
        timeAgo: '2 weeks ago',
        comments: 2,
        files: 0,
        assignee: { name: 'Sarah Johnson', avatar: 'https://i.pravatar.cc/150?u=sarahj' },
        reporter: { name: 'Alice Smith', avatar: 'https://i.pravatar.cc/150?u=alice' },
        slaRemaining: 'Resolved',
        slaPercentage: 100,
        timeline: [],
        attachments: []
    },
    {
        id: 'TK-2832',
        date: "2023-09-12",
        title: 'Audit Log Not Updating',
        agency: 'Alpha Corp',
        priority: 'High',
        status: 'In Progress',
        description: 'Audit logs for user deletion are not appearing in the global log stream.',
        timeAgo: '12 hours ago',
        comments: 4,
        files: 0,
        assignee: { name: 'Mike Chen', avatar: 'https://i.pravatar.cc/150?u=mike' },
        reporter: { name: 'Sarah Connor', avatar: 'https://i.pravatar.cc/150?u=sarah' },
        slaRemaining: '12h remaining',
        slaPercentage: 40,
        timeline: [],
        attachments: []
    },
    {
        id: 'TK-2831',
        date: "2023-09-20",
        title: 'Bulk Upload Validation Error',
        agency: 'Tech Innovations',
        priority: 'Medium',
        status: 'Open',
        description: 'Valid CSV files are failing validation with "Invalid Column Name" errors.',
        timeAgo: '2 hours ago',
        comments: 1,
        files: 3,
        assignee: { name: 'David Park', avatar: 'https://i.pravatar.cc/150?u=david' },
        reporter: { name: 'Bob Wilson', avatar: 'https://i.pravatar.cc/150?u=bob' },
        slaRemaining: '22h remaining',
        slaPercentage: 15,
        timeline: [],
        attachments: []
    },
    {
        id: 'TK-2830',
        date: "2023-10-01",
        title: 'License Key Invalid',
        agency: 'Digital Solutions Inc',
        priority: 'Critical',
        status: 'Pending',
        description: 'Agency license key shows as expired even though billing is up to date.',
        timeAgo: '1 hour ago',
        comments: 7,
        files: 1,
        assignee: { name: 'Sarah Johnson', avatar: 'https://i.pravatar.cc/150?u=sarahj' },
        reporter: { name: 'Eve Davis', avatar: 'https://i.pravatar.cc/150?u=eve' },
        slaRemaining: '3h remaining',
        slaPercentage: 80,
        timeline: [],
        attachments: []
    },
    {
        id: 'TK-2829',
        date: "2023-10-10",
        title: 'Session Timeout Too Short',
        agency: 'Creative Hub',
        priority: 'Low',
        status: 'Resolved',
        description: 'Users are being logged out after 15 minutes of inactivity. Need to increase to 60.',
        timeAgo: '3 weeks ago',
        comments: 4,
        files: 0,
        assignee: { name: 'Mike Chen', avatar: 'https://i.pravatar.cc/150?u=mike' },
        reporter: { name: 'John Doe', avatar: 'https://i.pravatar.cc/150?u=john' },
        slaRemaining: 'Resolved',
        slaPercentage: 100,
        timeline: [],
        attachments: []
    },
    {
        id: 'TK-2828',
        date: "2023-10-15",
        title: 'Notification Preferences Not Saving',
        agency: 'Marketing Pro',
        priority: 'Medium',
        status: 'Open',
        description: 'Toggling off email notifications reverts back to ON after page refresh.',
        timeAgo: '4 hours ago',
        comments: 2,
        files: 0,
        assignee: { name: 'David Park', avatar: 'https://i.pravatar.cc/150?u=david' },
        reporter: { name: 'Alice Smith', avatar: 'https://i.pravatar.cc/150?u=alice' },
        slaRemaining: '20h remaining',
        slaPercentage: 20,
        timeline: [],
        attachments: []
    },
    {
        id: 'TK-2827',
        date: "2023-10-22",
        title: 'Search Indexing Delay',
        agency: 'Alpha Corp',
        priority: 'High',
        status: 'In Progress',
        description: 'New documents are taking over 2 hours to appear in search results.',
        timeAgo: '6 hours ago',
        comments: 5,
        files: 0,
        assignee: { name: 'Sarah Johnson', avatar: 'https://i.pravatar.cc/150?u=sarahj' },
        reporter: { name: 'Sarah Connor', avatar: 'https://i.pravatar.cc/150?u=sarah' },
        slaRemaining: '6h remaining',
        slaPercentage: 50,
        timeline: [],
        attachments: []
    },
    {
        id: 'TK-2826',
        date: "2023-11-01",
        title: 'Integration Token Expired',
        agency: 'Tech Innovations',
        priority: 'Critical',
        status: 'Pending',
        description: 'Third-party integration failing due to an undocumented token expiration issue.',
        timeAgo: '2 hours ago',
        comments: 9,
        files: 1,
        assignee: { name: 'Mike Chen', avatar: 'https://i.pravatar.cc/150?u=mike' },
        reporter: { name: 'Bob Wilson', avatar: 'https://i.pravatar.cc/150?u=bob' },
        slaRemaining: '2h remaining',
        slaPercentage: 90,
        timeline: [],
        attachments: []
    },
    {
        id: 'TK-2825',
        date: "2023-11-05",
        title: 'Report PDF Formatting Issue',
        agency: 'Digital Solutions Inc',
        priority: 'Medium',
        status: 'Open',
        description: 'Exported PDF reports have overlapping text on the summary charts.',
        timeAgo: '1 day ago',
        comments: 1,
        files: 4,
        assignee: { name: 'David Park', avatar: 'https://i.pravatar.cc/150?u=david' },
        reporter: { name: 'Eve Davis', avatar: 'https://i.pravatar.cc/150?u=eve' },
        slaRemaining: '47h remaining',
        slaPercentage: 25,
        timeline: [],
        attachments: []
    },
    {
        id: 'TK-2824',
        date: "2023-11-12",
        title: 'Storage Quota Exceeded Error',
        agency: 'Creative Hub',
        priority: 'High',
        status: 'Resolved',
        description: 'Agency unable to upload files despite being well under the 50GB storage limit.',
        timeAgo: '1 month ago',
        comments: 8,
        files: 0,
        assignee: { name: 'Sarah Johnson', avatar: 'https://i.pravatar.cc/150?u=sarahj' },
        reporter: { name: 'John Doe', avatar: 'https://i.pravatar.cc/150?u=john' },
        slaRemaining: 'Resolved',
        slaPercentage: 100,
        timeline: [],
        attachments: []
    },
    {
        id: 'TK-2823',
        date: "2023-11-20",
        title: 'Avatar Upload Failing',
        agency: 'Marketing Pro',
        priority: 'Low',
        status: 'Open',
        description: 'Profile pictures fail to upload if the image is in WEBP format.',
        timeAgo: '5 hours ago',
        comments: 0,
        files: 1,
        assignee: { name: 'Mike Chen', avatar: 'https://i.pravatar.cc/150?u=mike' },
        reporter: { name: 'Alice Smith', avatar: 'https://i.pravatar.cc/150?u=alice' },
        slaRemaining: '19h remaining',
        slaPercentage: 15,
        timeline: [],
        attachments: []
    },
    {
        id: 'TK-2822',
        date: "2023-12-01",
        title: 'Duplicate Agency Records',
        agency: 'Alpha Corp',
        priority: 'High',
        status: 'In Progress',
        description: 'System created two identical agency profiles during signup.',
        timeAgo: '1 day ago',
        comments: 11,
        files: 0,
        assignee: { name: 'David Park', avatar: 'https://i.pravatar.cc/150?u=david' },
        reporter: { name: 'Sarah Connor', avatar: 'https://i.pravatar.cc/150?u=sarah' },
        slaRemaining: '11h remaining',
        slaPercentage: 60,
        timeline: [],
        attachments: []
    },
    {
        id: 'TK-2821',
        date: "2023-12-10",
        title: 'Role Permissions Denied',
        agency: 'Tech Innovations',
        priority: 'Medium',
        status: 'Pending',
        description: 'Managers cannot invite new users, getting a 403 Forbidden error.',
        timeAgo: '2 days ago',
        comments: 3,
        files: 0,
        assignee: { name: 'Sarah Johnson', avatar: 'https://i.pravatar.cc/150?u=sarahj' },
        reporter: { name: 'Bob Wilson', avatar: 'https://i.pravatar.cc/150?u=bob' },
        slaRemaining: '46h remaining',
        slaPercentage: 20,
        timeline: [],
        attachments: []
    },
    {
        id: 'TK-2820',
        date: "2024-01-05",
        title: 'Database Connection Pool Full',
        agency: 'Digital Solutions Inc',
        priority: 'Critical',
        status: 'Open',
        description: 'Service disruption due to Postgres connection pool exhaustion.',
        timeAgo: '15 mins ago',
        comments: 14,
        files: 2,
        assignee: { name: 'Mike Chen', avatar: 'https://i.pravatar.cc/150?u=mike' },
        reporter: { name: 'Eve Davis', avatar: 'https://i.pravatar.cc/150?u=eve' },
        slaRemaining: '3.75h remaining',
        slaPercentage: 95,
        timeline: [],
        attachments: []
    },
    {
        id: 'TK-2819',
        date: "2024-01-15",
        title: 'Analytics Dashboard Empty',
        agency: 'Creative Hub',
        priority: 'High',
        status: 'In Progress',
        description: 'Widgets on the main analytics dashboard are showing zero data for the past week.',
        timeAgo: '8 hours ago',
        comments: 6,
        files: 1,
        assignee: { name: 'David Park', avatar: 'https://i.pravatar.cc/150?u=david' },
        reporter: { name: 'John Doe', avatar: 'https://i.pravatar.cc/150?u=john' },
        slaRemaining: '4h remaining',
        slaPercentage: 75,
        timeline: [],
        attachments: []
    },
    {
        id: 'TK-2818',
        date: "2024-01-20",
        title: 'Unhandled Exception in API',
        agency: 'Marketing Pro',
        priority: 'Medium',
        status: 'Open',
        description: 'Null reference exception thrown when calling the /api/users endpoint without filters.',
        timeAgo: '1 day ago',
        comments: 2,
        files: 0,
        assignee: { name: 'Sarah Johnson', avatar: 'https://i.pravatar.cc/150?u=sarahj' },
        reporter: { name: 'Alice Smith', avatar: 'https://i.pravatar.cc/150?u=alice' },
        slaRemaining: '24h remaining',
        slaPercentage: 40,
        timeline: [],
        attachments: []
    }
];
